INSERT INTO products (name, price) VALUES ('Laptop', 1200.00);
INSERT INTO products (name, price) VALUES ('Smartphone', 699.99);
INSERT INTO products (name, price) VALUES ('Headphones', 99.50);
INSERT INTO products (name, price) VALUES ('Camera', 499.95);
INSERT INTO products (name, price) VALUES ('Fitness Tracker', 79.99);
INSERT INTO products (name, price) VALUES ('Coffee Maker', 49.95);
INSERT INTO products (name, price) VALUES ('Bluetooth Speaker', 59.99);
INSERT INTO products (name, price) VALUES ('External Hard Drive', 129.99);
INSERT INTO products (name, price) VALUES ('Smartwatch', 199.00);
INSERT INTO products (name, price) VALUES ('Gaming Console', 299.99);
INSERT INTO products (name, price) VALUES ('Tablet', 399.00);
INSERT INTO products (name, price) VALUES ('Desk Chair', 149.50);
INSERT INTO products (name, price) VALUES ('Printer', 89.95);
INSERT INTO products (name, price) VALUES ('LED TV', 799.99);
INSERT INTO products (name, price) VALUES ('Wireless Mouse', 19.99);
INSERT INTO products (name, price) VALUES ('Desk Lamp', 29.95);
INSERT INTO products (name, price) VALUES ('Router', 69.99);
INSERT INTO products (name, price) VALUES ('Home Theater System', 499.50);
INSERT INTO products (name, price) VALUES ('Blender', 39.99);
